package com.conygre.spring.boot.repos;

import com.conygre.spring.boot.entities.CompactDisc;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests for {@link CompactDiscRepository} against a real (H2,
 * in-memory) JPA provider.
 *
 * <p>Why this class exists in addition to the mocked service tests: the
 * mocked {@code CompactDiscServiceImplTest} never actually executes any JPA
 * query - it just stubs whatever the mock returns. In particular,
 * {@code findByArtist(String)} is a Spring Data JPA *derived query method*
 * with no explicit {@code @Query} - its behaviour is generated by Spring
 * Data at runtime from the method name, and that generated query is never
 * exercised anywhere else in this test suite. A typo or refactor of the
 * method name (e.g. to a property that doesn't exist on CompactDisc) would
 * only be caught here, at real persistence-context start-up/query time.
 *
 * <p>{@code @DataJpaTest} auto-configures an embedded, in-memory H2
 * database (h2 is a test-scope dependency in pom.xml) in place of the
 * MySQL datasource configured in src/main/resources/application.properties,
 * and wraps each test in a transaction that is rolled back afterwards, so
 * tests do not interfere with each other and require no running MySQL
 * instance.
 */
@DataJpaTest
class CompactDiscRepositoryTest {

    @Autowired
    private CompactDiscRepository repository;

    // ------------------------------------------------------------------
    // save() / identity generation
    // ------------------------------------------------------------------

    @Test
    @DisplayName("save() on a disc with id 0 persists it and generates a positive id (IDENTITY strategy)")
    void save_newDisc_generatesPositiveId() {
        CompactDisc disc = new CompactDisc("Is This It", 13.99, "The Strokes", 11);
        // id defaults to 0 (primitive int, never set)

        CompactDisc saved = repository.save(disc);

        assertTrue(saved.getId() > 0, "expected the database to assign a generated identity id");
    }

    @Test
    @DisplayName("findById() returns an empty Optional for an id that was never saved")
    void findById_unknownId_returnsEmptyOptional() {
        // Why this test exists: confirms, against a real JPA provider, the
        // exact Optional-based contract that CompactDiscServiceImpl relies
        // on (isPresent() check translating a miss into a null return, and
        // a raw .get() translating a miss into NoSuchElementException).
        Optional<CompactDisc> result = repository.findById(999999);

        assertFalse(result.isPresent());
    }

    @Test
    @DisplayName("findById() returns the saved entity for a known id")
    void findById_knownId_returnsEntity() {
        CompactDisc disc = new CompactDisc("Parachutes", 11.99, "Coldplay", 10);
        CompactDisc saved = repository.save(disc);

        Optional<CompactDisc> result = repository.findById(saved.getId());

        assertTrue(result.isPresent());
        assertEquals("Parachutes", result.get().getTitle());
    }

    // ------------------------------------------------------------------
    // findAll() on an empty table
    // ------------------------------------------------------------------

    @Test
    @DisplayName("findAll() returns an empty (not null) result when the table has no rows")
    void findAll_emptyTable_returnsEmptyIterable() {
        // Why this test exists: @DataJpaTest starts each test with a clean,
        // rolled-back-per-test schema and no data.sql on the classpath, so
        // this exercises the genuinely empty-catalog case at the real
        // persistence layer (complementary to the mocked-empty-list test in
        // CompactDiscServiceImplTest, which never touches real SQL).
        Iterable<CompactDisc> all = repository.findAll();

        assertFalse(all.iterator().hasNext());
    }

    // ------------------------------------------------------------------
    // findByArtist() - the one hand-written query method
    // ------------------------------------------------------------------

    @Test
    @DisplayName("findByArtist() returns only the discs matching that exact artist")
    void findByArtist_matchingArtist_returnsOnlyThoseDiscs() {
        repository.save(new CompactDisc("Is This It", 13.99, "The Strokes", 11));
        repository.save(new CompactDisc("Room On Fire", 12.99, "The Strokes", 11));
        repository.save(new CompactDisc("Parachutes", 11.99, "Coldplay", 10));

        Iterable<CompactDisc> found = repository.findByArtist("The Strokes");
        List<CompactDisc> results = StreamSupport.stream(found.spliterator(), false)
                .collect(Collectors.toList());

        assertEquals(2, results.size());
        assertTrue(results.stream().allMatch(d -> d.getArtist().equals("The Strokes")));
    }

    @Test
    @DisplayName("findByArtist() returns an empty result for an artist with no discs")
    void findByArtist_unknownArtist_returnsEmptyIterable() {
        // Why this test exists: verifies the "no matches" branch of a
        // derived query method - proving it returns a clean empty
        // collection rather than null or throwing, which the mocked
        // service tests cannot prove since they never run the real query.
        repository.save(new CompactDisc("Parachutes", 11.99, "Coldplay", 10));

        Iterable<CompactDisc> found = repository.findByArtist("Some Artist With No Albums");

        assertFalse(found.iterator().hasNext());
    }

    @Test
    @DisplayName("findByArtist() is case-SENSITIVE by default, so a differently-cased query finds nothing")
    void findByArtist_isCaseSensitiveByDefault() {
        // Why this test exists: Spring Data JPA derived query methods
        // (like "findByArtist") are, by default, case-sensitive equality
        // comparisons unless the method is explicitly declared with
        // "IgnoreCase" (e.g. findByArtistIgnoreCase). This is a real,
        // easy-to-miss surprise for API consumers who might expect a
        // search-style, case-insensitive match. This test documents the
        // actual current behaviour so nobody assumes case-insensitivity
        // without checking.
        repository.save(new CompactDisc("Is This It", 13.99, "The Strokes", 11));

        Iterable<CompactDisc> found = repository.findByArtist("the strokes");

        assertFalse(found.iterator().hasNext(), "expected no match because findByArtist is case-sensitive");
    }

    // ------------------------------------------------------------------
    // delete()
    // ------------------------------------------------------------------

    @Test
    @DisplayName("delete() removes the row so a subsequent findById() is empty")
    void delete_removesEntity() {
        CompactDisc saved = repository.save(new CompactDisc("Mezzanine", 12.99, "Massive Attack", 11));
        int id = saved.getId();

        repository.delete(saved);

        assertFalse(repository.findById(id).isPresent());
    }
}
